# This is a basic workflow to help you get started with Actions

name: Metrics (rem)

# Controls when the workflow will run
on:
  schedule: 
    - cron: "0 * * * *" # every one hour
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
      runs-on: ubuntu-latest
      name: generate-github-3d-contrib
      steps:
        - uses: actions/checkout@v2
        - uses: yoshi389111/github-profile-3d-contrib@0.4.0
          env:
            USERNAME: ${{ github.repository_owner }}
            GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
        - name: Commit & Push
          run: |
            git config user.name riimuru
            git config user.email mythhb@yahoo.com
            git add -A .
            git commit -m "Generated: Update README"
            git push
        - uses: lowlighter/metrics@latest
          with:
              template: terminal
              filename: metrics.terminal.svg
              token: ${{ secrets.METRICS_TOKEN }}
              base: header, metadata
          
        
        

